language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-noyobo' ]; then cd .. && eval "mv $currentfolder generator-noyobo" && cd generator-noyobo; fi

